version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: ipproxypool_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ipproxypool-network # IPProxyPool専用ネットワークに接続

  ipproxypool:
    build: .
    container_name: ipproxypool_app
    command: python main.py
    environment:
      - WEB_API_PORT=16888 # READMEに記載のポート
    volumes:
      - .:/app
    depends_on:
      - mongodb
    networks:
      - ipproxypool-network # IPProxyPool専用ネットワークに接続

volumes:
  mongodb_data:

networks:
  ipproxypool-network:
    driver: bridge